model_list:
# OpenAI/AZURE
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-5.2
    litellm_params:
      model: openai/gpt-5.2-2025-12-11
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: whisper-1
    litellm_params:
      model: openai/whisper-1
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: tts-1
    litellm_params:
      model: openai/tts-1
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-5.1-azure
    litellm_params:
      model: azure/gpt-5.1
      api_key: os.environ/AZURE_OPENAI_API_KEY
      api_base: https://chi-tech-demos.cognitiveservices.azure.com
      api_version: "2025-01-01-preview"

# Anthropic models
  - model_name: claude-4.5-haiku
    litellm_params:
      model: anthropic/claude-haiku-4-5-20251001
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: claude-4.5-opus
    litellm_params:
      model: anthropic/claude-opus-4-5-20251101
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: claude-4-6-sonnet
    litellm_params:
      model: anthropic/claude-sonnet-4-6
      api_key: os.environ/ANTHROPIC_API_KEY
      thinking: {"type": "enabled", "budget_tokens": 1024}
      merge_reasoning_content_in_choices: true
#Google
#  - model_name: gemini-2.5-pro
#    litellm_params:
#      model: gemini/gemini-2.5-pro
#      api_key: os.environ/GEMINI_API_KEY
#Mistral
  - model_name: mistral-small
    litellm_params:
      model: azure/mistral-small-2503
      api_base: https://chi-tech-demos.cognitiveservices.azure.com
      api_key: os.environ/MISTRAL_API_KEY
      api_version: "2024-05-01-preview"

# Image Generation Models
  - model_name: dall-e-3
    litellm_params:
      model: openai/dall-e-3
      api_key: os.environ/OPENAI_API_KEY
      size: "1024x1024"  # Options: 1024x1024, 1792x1024, 1024x1792
      quality: "standard"  # Options: standard, hd
      n: 1

  - model_name: dall-e-2
    litellm_params:
      model: openai/dall-e-2
      api_key: os.environ/OPENAI_API_KEY
      size: "1024x1024"  # Options: 256x256, 512x512, 1024x1024
      n: 1

  - model_name: gpt-image-1
    litellm_params:
      model: openai/gpt-image-1
      api_key: os.environ/OPENAI_API_KEY
      size: "1024x1024"  # Options: 1024x1024, 1536x1024, 1024x1536
      quality: "auto"  # Options: auto, high, medium, low

 # Add your Ollama models
  - model_name: llama3.2
    litellm_params:
      model: ollama/llama3.2
      api_base: http://ollama:11434

litellm_settings:
  drop_params: true
  set_verbose: true
  extra_spend_tag_headers:
    - "x-custom-header"
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  user_header_mappings:
    - header_name: X-OpenWebUI-User-Name
      litellm_user_role: internal_user
    - header_name: X-OpenWebUI-User-Email
      litellm_user_role: customer

